### ISSUE TITLE
Checkout steps get stuck on COL environment

### ISSUE THREAD

**Issue by ojuan19** [vtex-apps/checkout-step-group#17]
**Describe the bug**
I'm debugging this series of checkout-IO APPS, in this test environment **juan--norhlatamprojects.myvtex.com**, I installed the apps succesfully, on top vtex.checkout, and then checkout-step-group, whenever I try to continue the flow of a normal purchase, or modify some data (profile, shipping, payment) The whole page get stuck in the same anchor (#), that means: if I try to modify the #profile, then it's impossible to continue.

**To Reproduce**

1. Go to **https://juan--northlatamprojects.myvtex.com/**
2. Add something to cart and go to Checkout
3. Click on 'Edit profile data'
3. Try to change something
4. Then try to continue the checkout process (The app intents to continue but the router put it back on #profile again)
**Expected behavior**

**Screenshots**
<img width="1297" alt="Captura de Pantalla 2020-09-21 a la(s) 2 07 43 p  m" src="https://user-images.githubusercontent.com/64972735/93810718-abcb6300-fc14-11ea-9aef-fab0e7e13f27.png">
<img width="817" alt="Captura de Pantalla 2020-09-21 a la(s) 2 09 29 p  m" src="https://user-images.githubusercontent.com/64972735/93810744-b4bc3480-fc14-11ea-8a1b-0150c601d845.png">

**Desktop environment:**

System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 189.34 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Safari: 13.1

Please let me know if you need more context to find the root cause of this unexpected behavior.

**Comment by garrucho** [comment]
[As explained](https://vtex.slack.com/archives/C6HS68DHD/p1600719227078000?thread_ts=1600717760.077300&cid=C6HS68DHD), this app still as WIP.
